### PR TITLE
add instructions and samples for hashing and verification

### PR DESCRIPTION
**Pull request by trentlarson**
# Justification

These documents can be extremely useful for automated comparison and validation, so this is my proposal for versions of the MNDA contract that will support these cryptographic operations.

Hopefully the README-VERIFY.md document makes sense and is adequate justification. If not, let me know what you would like added/changed to make this an official part of the specification. If these additional features are not things that you'd like to consider in the Common Paper organization, I'm fine hosting a fork... but let me know if there's any way to start some collaboration, even if it's just a link to my own side for some enhanced tooling that adds to your basic contracts.

This may well end up as a separate set of documents (which we could mechanically derive from the base text). For example, this version includes the Party details of Name, Title, Company, Notice Address, Date (and any other parameters) as a single multi-line variable in the document; I explain my reasons for inclusion in README-VERIFY.md and I think it makes sense to make my version here into the canonical base version.

Note that I don't recommend inclusion of a Signature, since that would be a separate artifact (eg. a cryptographic signature or an image of a wet signature on a copy).

Many of these choices can be discussed, of course.

I look forward to building even more on top of these contracts, such as use in a [KERI](https://keri.one/) ecosystem (eg. inclusion of [SAID](https://www.ietf.org/archive/id/draft-ssmith-said-02.html) and sharing via [CESR](https://github.com/SmithSamuelM/Papers/blob/master/presentations/CESR_Overview.web.pdf)).

### Note on the variable formatting

To mark the contract variables, the current base version uses `span` HTML tags, where the copy in this PR uses `{{...}}` delimiters. The span tag has the benefit of enabling browser JavaScript functionality; however, that approach results in a downside as well (the first item below).

The delimiter approach has the following benefits:

* The variables are clear (whereas in an HTML `span` they are not clearly visually distinguishable by default). They are obvious even when copying and pasting elsewhere.

* There is no opinionated tagging in a particular format; the formatting is fully left up to the renderer.

* It follows a separate specification for variable substitution; the non-formatting rules are not mixed with formatting rules.

Note that I also have a version of the current HTML-delimited contract, which we could add if there is motivation to use that format as well: https://github.com/trentlarson/CommonPaper-Mutual-NDA/commit/bee65559f4fc0d596e5743f60462f348f7e7b03e

### CODE REVIEW

**Comment by bengarvey** [comment]
Hi @trentlarson! Love to see this and I'll review it today.

**Comment by trentlarson** [comment]
In case you don't have a nice IDE to show text differences, here's an online tool to see the difference character-by-character: https://diffviewer.com/textdiff

To compare my diffs, paste the contents from [the main version](https://raw.githubusercontent.com/CommonPaper/Mutual-NDA/main/Mutual-NDA.md) and [my version](https://raw.githubusercontent.com/trentlarson/CommonPaper-Mutual-NDA/lmd-preimage/Mutual-NDA-preimage-lmd.md)

**Comment by trentlarson** [comment]
A few formatting notes for humans that I now realize are different with a self-contained version:

- The current version still includes references to the Cover Page. This may be appropriate if there are instructions that describe how the Cover Page can mean a separate sheet OR concatenated contents, or it may be more appropriate to modify the wording.

- The "Changes to Standard Terms" should probably be a separate section rather than as item # 12 inside the "Standard Terms" section.

- It does not have a title on the top, which makes it appear incomplete.

**Comment by trentlarson** [comment]
Note that I am willing to contribute more instructions and open-source code that will parse the contents and validate against hash values.

**Comment by bengarvey** [comment]
Hey @trentlarson, so I think there's a misunderstanding here about how these agreements are intended to be used that can be cleared up by looking at our README and this page https://commonpaper.com/standards/

The standard terms are immutable and we don't need to do a find and replace for their values. When using the NDA you send a coversheet indicating the values for the defined terms and link to the terms by reference. 
https://commonpaper.com/standards/mutual-nda/1.0

Would love to chat this week to talk more about what you're trying to accomplish and how we can help. Email me ben@commonpaper.com

**Comment by trent-medici** [comment]
Note that it's straightforward to use [Pandoc](https://pandoc.org/) to render the final contract, where the variables are substituted in the text and the output is available in a number of formats. It currently requires a different set of delimiters: `$..$` or `${...}`

If one uses those delimiters in my sample (instead of `{{...}}`) and places something like this at the front:

```
---
Party_1_Details: |-
  Thomas Jefferson
  Monticello, VA
---
```

... then the final document be rendered in HTML with this command: `pandoc test.md --template test.md | pandoc -t html > test.html`

Other details:

* This is just one rendering, and this output shouldn't be used for cryptographic checks because the output isn't guaranteed to follow a standard format.

* There's another format called [MultiMarkdown](https://fletcherpenney.net/multimarkdown/) that uses `[%...]` delimiters. There are discussions about ways to customize variable delimiters like [this](https://github.com/michaelstepner/pandoc-mustache/issues/4) but I've found no concrete solution yet.

**Comment by ekryski** [comment]
@trent-medici I like where your head is at here! We're a Pandadoc user and I also have a personal interest in DIDs and leveraging cryptography for automation and enforcement.

Maybe to clarify your intent,

> You're aiming to have a common core document where a checksum can be computed so that a machine can verify the document is not faked or hasn't been tampered with. Ideally signed with a private key that is associated to or own a DID.

Is this correct? 👆

If so, I think this is going in the right direction. I agree with @bengarvey that I think the `Changes in standard terms` section should be omitted for this version so v1 stays immutable. Possibly it could be a v2 that supports some more dynamic modifications to the standard but it's really the cover page that is dynamic and references the standard.

Based on my read, here are some suggested changes (take it or leave it):

1. The cover page contains the dynamic party details. Compute a checksum of that doc, like you're doing with the standard agreement. This is the one that would be fillable with party details like you're suggesting @trentlarson;

2. Update [Mutual-NDA-coverpage.md](https://github.com/CommonPaper/Mutual-NDA/blob/main/Mutual-NDA-coverpage.md) to support the programmatic find & replace delimiters that @trent-medici suggested. 

3. Leave the standard agreement as is (because as @bengarvey mentioned it's referenced as an additional item by the cover page) and have a pre-imaged checksum of the standard v1 version to compare against.

4. Update the [README.md](https://github.com/CommonPaper/Mutual-NDA/blob/main/README.md) to explain how you'd programatically you'd fill in the dynamic components of the cover page, and compute and compare the checksums of both the cover page and the standard doc;

Happy to put up a PR or assist if you think this is correct. Exciting stuff! 🙂

> **Note:** I stumbled across this randomly but have been thinking about legal document automation + crypto for ~7 years now. I don't work for Common Paper so this is just unsolicited feedback from someone who had a similar thought around "could I pipe this into Pandadoc or sign with a private key?" 🙂

**Comment by trentlarson** [comment]
> Maybe to clarify your intent,

> You're aiming to have a common core document where a checksum can be computed so that a machine can verify the document is not faked or hasn't been tampered with.

Yes. Put yet another way: as lawyers & customers pass agreements back and forth, they can be sure that the basic terms of the document are terms that A) they have seen before, and even B) are vetted and used by others in their ecosystem. A machine can verify that most terms are as expected and humans can check the smaller set of specific distinguishing terms for their engagement.

> Ideally signed with a private key that is associated to or own a DID.

Yeah, this would enable other services for signing, etc. Of course, there is value in the hash alone: even without signatures, users can be sure that they're working with a standard.

Ben was kind enough to discuss these items with me directly. I've made some edits that I hope will address some of the feedback you've both given.

FYI, I have written my proposed version into a mobile app that allows signing of the full document. You can see the structure [here](https://github.com/trentlarson/endorser-mobile/blob/15dcb89ccdcc1e74f0b4b2015f4b1c04566ef313/src/data/onboarding.ts#L176). Note that I've been using IPFS CIDv0 hashes, eg. in the variable `templateIpfsCid`.

Maybe it's worth comparing our use cases and creating more shared tooling; we can build interesting tools on top of these hashes, along with other open standards.

I'm glad to see your interest! If CommonPaper is open to publication of these hashes -- or, better, if they show interest in our additional tooling (even if just a shout-out to our third-party contributions), this could be fun.

**Comment by trentlarson** [comment]
I've made some edits that more clearly target the purpose of sharing hashes (and I've removed other changes like different delimiters and variable names).

So this is one more attempt at a set of files in the CommonPaper repo that will be acceptable... not changing any of the core files (except the README), but adding some optional files that enable more automated validation as parties share these contracts with their own details.

**Comment by bengarvey** [comment]
@trentlarson Going to close this as I don't it aligns with what we're trying to do with reference-able terms and cover sheet params.

**Pull request closed without merging**
